language: node_js
node_js: '12'
cache: yarn

env:
    global:
        - GITHUB_ORG="https://GH_TOKEN@github.com"
        - REPO_NAME="ng-periodic-table"
        - GITHUB_NAME="railsstudent"
        - GITHUB_EMAIL="cleung334@gmail.com"

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
    local-dir: dist/

before_script:
    - yarn install

script:
    - echo "*** audit ***"
    - yarn audit
    - echo "*** lint ***"
    - yarn lint
    - echo "*** Build production build ***"
    - ng build --prod

after_success:
    - echo "*** Deploy ng-periodic-table to github pages ****"
    - ng deploy --base-href=/ng-periodic-table/ --repo="$GITHUB_ORG/$GITHUB_NAME/$REPO_NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --no-silent

branches:
    only:
        - master

notifications:
    email:
        recipients:
            - $GITHUB_EMAIL
        on_success: never # default: change
        on_failure: always # default: always
