language: node_js
node_js: '8'
cache: yarn

env:
    global:
        - GITHUB_ORG="https://GH_TOKEN@github.com"
        - REPO_NAME="ng-periodic-table"
        - GITHUB_NAME="railsstudent"
        - GITHUB_EMAIL="cleung334@gmail.com"

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
    local-dir: dist/

before_script:
    - yarn install

script:
    - echo "*** lint ***"
    - yarn lint
    - echo "*** Build production build ***"
    - ng build --prod --base-href "https://railsstudent.github.io/ng-periodic-table/"
    - echo "*** Deploy ng-periodic-table to github pages ****"
    - ngh --repo="$GITHUB_ORG/$GITHUB_NAME/$REPO_NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --no-silent

after_success:
    - ngh --repo="$GITHUB_ORG/$GITHUB_NAME/$REPO_NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --no-silent

branches:
    only:
        - master

notifications:
    email:
        recipients:
            - $GITHUB_EMAIL
        on_success: never # default: change
        on_failure: always # default: always
